version: '3.9'
services: 
  db:
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jet